name: release

on:
  push:
    tags:
      - 'v\d+'

permissions:
  issues: write
  contents: read

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yml
  create-release-issue:
    runs-on: ubuntu-22.04
    needs: run-tests
    steps:
      - uses: actions/checkout@v3
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: ${{ github.actor }}
          VERSION: ${{ github.ref_name }} 
          JOB_URL_E2E_TESTS: ${{ needs.run-tests.outputs.e2e-job-url }}
          JOB_URL_UNIT_TESTS: ${{ needs.run-tests.outputs.unit-job-url }}
          CHANGELOG: ${{ steps.changelog.outputs.changes }}
        with:
          update_existing: true