name: release

on: [push]

permissions:
  issues: write
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    outputs:
      run-tests:  ${{ steps.tests_url.outputs.TESTS_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/tests.yml
      - name: Output action URL
        id: tests_url
        run: echo "TESTS_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
  create-release-issue:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: author_test
          DATE: date_test
          VERSION: version_test
          TESTS: ${{needs.run-tests.outputs.run-tests}}
          CHANGELOG: ${{ steps.changelog.outputs.changes }}
        with:
          update_existing: true
    needs: [run-tests]