name: release

on:
  push:
    tags:
      - 'v\d+'

permissions:
  issues: write
  contents: write

jobs:
  create-changelog:
    runs-on: ubuntu-22.04
    outputs:
      changes: ${{ steps.changelog.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: requarks/changelog-action@v1
        id: changelog
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

  create-release-issue:
    runs-on: ubuntu-22.04
    needs: create-changelog
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: ${{ github.actor }}
          VERSION: ${{ github.ref_name }}
          TESTS: running tests...
          CHANGELOG: ${{ needs.create-changelog.outputs.changes }}
        with:
          update_existing: true

  run-tests:
    uses: ./.github/workflows/tests.yml

  issue-add-tests-results:
    runs-on: ubuntu-22.04
    needs: [run-tests, create-release-issue, create-changelog]
    outputs:
      issue-number: ${{ steps.create-issue.outputs.number }}
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: ${{ github.actor }}
          VERSION: ${{ github.ref_name }}
          TESTS: "[Tests results](${{ needs.run-tests.outputs.tests-job-url }})"
          CHANGELOG: ${{ needs.create-changelog.outputs.changes }}
        with:
          update_existing: true

  deploy:
    needs: run-tests
    uses: ./.github/workflows/deploy.yml

  add-deploy-comment:
    runs-on: ubuntu-22.04
    needs: [deploy, issue-add-tests-results]
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ needs.issue-add-tests-results.outputs.issue-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployed successfully! 🚀'
            })

  close-issue:
    runs-on: ubuntu-22.04
    needs: [add-deploy-comment, issue-add-tests-results]
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ needs.issue-add-tests-results.outputs.issue-number }},
              state: "closed",
              state_reason: "completed"
            })