name: tests

on:
  push:
    branches: ['tests']

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Run unit tests"
        run: |
          npm ci
          npm run test-ci

  e2e-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Run e2e tests"
        run: |
          npm ci
          npx playwright install --with-deps chromium
          CI=true npm run e2e
